server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称用于binding整合
          type: rabbit #消息组件类型
          #environment:  #设置rabbitmq的相关的环境配置
           # spring:
            #  rabbitmq:
             #   host: localhost
              #  port: 5672
               # username: huasheng
                #password: huasheng
      bindings:  #服务的整合处理
        input:   #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义 交互机
          content-type: application/json #设置消息类型 本次为json
          binder:  defaultRabbit  #设置要绑定的消息服务的具体设置
          group: atguiguA

eureka:
  instance:
    lease-renewal-interval-in-seconds: 2 #心跳时间
    lease-expiration-duration-in-seconds: 5 #超时5秒间隔
    instance-id: receive-8802.com #在信息列表时显示主机名称
    prefer-ip-address: true #访问路径变为ip地址
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
rabbitmq:
  port: 5672
  host: localhost
  username: huasheng
  password: huasheng
