server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
  zipkin:  #链路追踪配置
      base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1    #采样 0到1之间

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sun.springcloud.entities  #所有entity别名所在包
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: payment8001 #主机名称
    prefer-ip-address: true #访问路径可以显示ip地址
    #下面是实现AP的设置
    #Eureka客户端向服务端发送心跳的时间间隔默认为30秒
    lease-renewal-interval-in-seconds: 1
    #eureka服务收到最后一次心跳后等待的时间上限 默认90秒 超时剔除服务
    lease-expiration-duration-in-seconds: 2
